# Generated by Django 3.2.6 on 2021-09-29 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('quiz_id', models.CharField(max_length=32)),
                ('quetsion_id', models.CharField(max_length=32)),
                ('text', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=32)),
                ('text', models.TextField(max_length=2048)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date_started', models.DateField(default=datetime.datetime.now)),
                ('date_ended', models.DateField(null=True)),
                ('description', models.TextField(max_length=512)),
            ],
        ),
    ]
