# Generated by Django 3.2.6 on 2021-09-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quetsion_id',
            new_name='question_id',
        ),
    ]
